apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority
value: -10
preemptionPolicy: Never
globalDefault: false
description: "This priority class is meant to be used with scavenger jobs."