# Maybe can be added as part of a defaulting webhook, to ensure that the jobs are created with the right priority class
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority-sj-nonpreempting
value: -10
preemptionPolicy: Never
globalDefault: false
description: "This priority class is meant to be used with scavenger jobs."