---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-cerit-cz-v1-scavengerjob
  failurePolicy: Fail
  name: mscavengerjob.kb.io
  rules:
  - apiGroups:
    - core.cerit.cz
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scavengerjobs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-cerit-cz-v1-scavengerjob
  failurePolicy: Fail
  name: vscavengerjob.kb.io
  rules:
  - apiGroups:
    - core.cerit.cz
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scavengerjobs
  sideEffects: None
