---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - k8s.io.my.domain
  resources:
  - scavengerjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.io.my.domain
  resources:
  - scavengerjobs/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.io.my.domain
  resources:
  - scavengerjobs/status
  verbs:
  - get
  - patch
  - update
