apiVersion: core.cerit.cz/v1
kind: ScavengerJob
metadata:
  labels:
    app.kubernetes.io/name: scavengerjob
    app.kubernetes.io/instance: scavengerjob-sample
    app.kubernetes.io/part-of: scavenger-jobs-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: scavenger-jobs-operator
  name: scavengerjob-sample
spec:
  job:
    template:
      spec:
        securityContext:
          fsGroupChangePolicy: OnRootMismatch
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        containers:
          - name: echo
            image: busybox
            command: ["echo", "Hello, World!"]
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
            securityContext:
              runAsUser: 1000
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
        restartPolicy: Never
    backoffLimit: 1

