apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-infinity-COUNT
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: busybox
        command: ["sleep", "infinity"]
      restartPolicy: Never
