apiVersion: core.cerit.cz/v1
kind: ScavengerJob
metadata:
  name: sleepy-scavengerjob-COUNT
spec:
  foo: sleepy
  job:
    template:
      spec:
        containers:
          - name: sleep
            image: busybox
            command: ["sleep", "infinity"]
            imagePullPolicy: Never
        restartPolicy: Never
    backoffLimit: 1

